name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  CONTAINS_SKIP: ${{ contains(join(github.event.commits.*.message), '#skip') }}

jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      SKIP_PREFLIGHT_CHECK: true
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run lint:check

      - name: Build front-end
        run: npm run build

      - name: Run tests
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:e2e
          start: npm run start:test
          wait-on: http://localhost:3001

      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}
        if: ${{ github.event_name == 'push' }}

      - name: Successful deployment
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          text: A new version of Bloglist deployed
          details: to ${{ github.repository }} by ${{ github.event.head_commit.author.username }}
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Unsuccessful deployment
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          text: Build failed
          description: commit
          details: https://github.com/${{ github.repository }}/commit/${{ github.sha }} by ${{ github.event.head_commit.author.username }} broke the build
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  tag_release:
    needs: [deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        if: ${{ github.event_name == 'push' && env.CONTAINS_SKIP == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
